// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: shredstream.proto

package shredstream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEntriesRequest) Reset() {
	*x = SubscribeEntriesRequest{}
	mi := &file_shredstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEntriesRequest) ProtoMessage() {}

func (x *SubscribeEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shredstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEntriesRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEntriesRequest) Descriptor() ([]byte, []int) {
	return file_shredstream_proto_rawDescGZIP(), []int{0}
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Entries       []byte                 `protobuf:"bytes,2,opt,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_shredstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_shredstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_shredstream_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *Entry) GetEntries() []byte {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_shredstream_proto protoreflect.FileDescriptor

const file_shredstream_proto_rawDesc = "" +
	"\n" +
	"\x11shredstream.proto\x12\vshredstream\"\x19\n" +
	"\x17SubscribeEntriesRequest\"5\n" +
	"\x05Entry\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12\x18\n" +
	"\aentries\x18\x02 \x01(\fR\aentries2b\n" +
	"\x10ShredstreamProxy\x12N\n" +
	"\x10SubscribeEntries\x12$.shredstream.SubscribeEntriesRequest\x1a\x12.shredstream.Entry0\x01b\x06proto3"

var (
	file_shredstream_proto_rawDescOnce sync.Once
	file_shredstream_proto_rawDescData []byte
)

func file_shredstream_proto_rawDescGZIP() []byte {
	file_shredstream_proto_rawDescOnce.Do(func() {
		file_shredstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shredstream_proto_rawDesc), len(file_shredstream_proto_rawDesc)))
	})
	return file_shredstream_proto_rawDescData
}

var file_shredstream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shredstream_proto_goTypes = []any{
	(*SubscribeEntriesRequest)(nil), // 0: shredstream.SubscribeEntriesRequest
	(*Entry)(nil),                   // 1: shredstream.Entry
}
var file_shredstream_proto_depIdxs = []int32{
	0, // 0: shredstream.ShredstreamProxy.SubscribeEntries:input_type -> shredstream.SubscribeEntriesRequest
	1, // 1: shredstream.ShredstreamProxy.SubscribeEntries:output_type -> shredstream.Entry
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shredstream_proto_init() }
func file_shredstream_proto_init() {
	if File_shredstream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shredstream_proto_rawDesc), len(file_shredstream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shredstream_proto_goTypes,
		DependencyIndexes: file_shredstream_proto_depIdxs,
		MessageInfos:      file_shredstream_proto_msgTypes,
	}.Build()
	File_shredstream_proto = out.File
	file_shredstream_proto_goTypes = nil
	file_shredstream_proto_depIdxs = nil
}
